export const BASE_URL = "https://sendme.xb.uz/";
export const ENDPOINTS = {
    getMe: 'api/v1/auth/me',
    identity: 'api/v1/auth/identity',
    login: 'api/v1/auth/sign-in',
    translations: 'api/v1/site/translations',
    count: 'api/v1/docflow/doc-flow/count-new',
    departmentDaily: 'api/v1/docflow/dashboard/department-daily',
    incoming: 'api/v1/docflow/doc-flow-doc-flow-incoming',
    outgoing: 'api/v1/docflow/doc-flow-doc-flow-outgoing',
    report: 'api/v1/docflow/doc-flow-doc-flow-notification',
    mobileAuth: 'frontend/mobile/auth',
    mobileSign: 'frontend/mobile/sign',
    mobileStatus: 'frontend/mobile/status',
    loginByMobileAuth: 'api/v1/auth/login-with-doc-id',
    docflowResolutionSignWithoutKey: 'api/v1/docflow/docflow-cert-sign/sign-without-key',
    documentAccept: 'api/v1/docflow/refactoring/accept',
    docflowFile: 'api/v1/docflow/doc-flow-file',
    reject: 'api/v1/docflow/refactoring/reject',
    signMobile: 'api/v1/docflow/docflow-cert-sign/sign-mobile-eimzo',
}

export const KEYS = {
    getMe: 'getMe',
    identity: 'identity',
    login: 'login',
    translations: 'translations',
    count: 'count',
    departmentDaily: 'departmentDaily',
    incoming:'incoming',
    outgoing:'outgoing',
    report:'report',
    mobileAuth:'mobileAuth',
    mobileSign:'mobileSign',
    loginByMobileAuth:'loginByMobileAuth',
    docflowResolutionSignWithoutKey:'docflowResolutionSignWithoutKey',
    documentAccept:"documentAccept",
    docflowFile:'docflowFile'
}
export const DOC_TYPES = {
    incoming: "docflow\\models\\DocflowDocFlowIncoming",
    outgoing: "docflow\\models\\DocflowDocFlowOutgoing",
    internal: "docflow\\models\\DocflowDocFlowInternal",
    report: "docflow\\models\\DocflowDocFlowNotification",
    correspondence: "docflow\\models\\DocflowDocFlowCorrespondence",
    executive: "docflow\\models\\DocflowDocFlowExecutive",
    resolution: "docflow\\models\\DocflowResolution",
    cardCheckpoint: "docflow\\models\\DocflowControlCardCheckpoint",
    reference: "docflow\\models\\DocflowDocFlowReference",
}
export const LANGUAGES = [{lang:'uz',title:'UZ'},{lang:'ru',title:'RU'},{lang:'en',title:'EN'}]

export const STATUS_LIST = {
    new: "new",
    newed: "newed",
    registered: "registered",
    on_resolution: "on_resolution",
    on_execution: "on_execution",
    on_register: "on_register",
    executed: "executed",
    not_executed: "not_executed",
    deadline_on_time: "deadline_on_time",
    deadline_overdue: "deadline_overdue",
    on_check_department: "on_check_department",
    on_check_registrar: "on_check_registrar",
    on_check_control_card_controller: "on_check_control_card_controller",
    reject_department: "reject_department",
    reject_registrar: "reject_registrar",
    reject_control_card_controller: "reject_control_card_controller",
    accept_department: "accept_department",
    accept_registrar: "accept_registrar",
    accept_control_card_controller: "accept_control_card_controller",
    on_sign: "on_sign",
    on_checker_sign: "on_checker_sign",
    reject_checker_sign: "reject_checker_sign",
    accept_checker_sign: "accept_checker_sign",
    reject_sign: "Откленоно подпись",
    accept_sign: "reject_sign",
    on_signed: "on_signed",
    on_checker_chairman: "on_checker_chairman",
    on_chairman: "on_chairman"
};